version: '3.7'
services:
  php-apache:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html/
    ports:
      - 80:80
    environment:
        - TZ=Europe/Moscow
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    #volumes:
      #- /var/lib/docker/volumes/9c3dd74da406ed3da7450e371667bb44973c49cce84e59bb0ddf0c40159d1df7/_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8080:80


      #docker exec -it php-apache sh connect to container
      #composer create-project symfony/skeleton:"6.3.*" .  instal symfony on composer

      

# если при работе показывается ошибка 404 или 5хх не из ларавель - значит не настроен хост корректно в апаче  
# включаем реврайт модуль в апаче a2enmod rewrite потом service apache2 restart
# добавляем в файл конфигуррации хоста 
#<Directory /var/www/html/public>
#        Options Indexes FollowSymLinks
#        AllowOverride All
#        Require all granted
#</Directory>
#
#
# composer create-project laravel/laravel:^8 .   ***install laravel 8***
#
# composer require barryvdh/laravel-debugbar --dev  ***install debugbar***

# composer require directorytree/ldaprecord-laravel   ***ldap***  https://ldaprecord.com/docs/laravel/v1/installation
# php artisan vendor:publish --provider="LdapRecord\Laravel\LdapServiceProvider"
# прописывание настроек ldap в файле .env
# php artisan ldap:test ***проверка работы ldap***
# ##
